### PR TITLE
Django 2.2 compatibility fix

### PR DESCRIPTION
**Pull request by arbrandes**
This allows the plugin to run under Django 2.2.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
There are a few more references to Django: https://github.com/open-craft/labxchange-xblocks/search?q=django&unscoped_q=django

e.g. can you please delete `manage.py` and `test_settings.py` too?

**Comment by arbrandes** [comment]
> There are a few more references to Django:
(...)
> e.g. can you please delete `manage.py` and `test_settings.py` too?

Yeah, sure!  All this does so far is avoid LMS startup errors - I hadn't done a full sweep, yet.

**Comment by arbrandes** [comment]
@bradenmacdonald, it seems some tox functionality, including document creation and PII annotation tests, depend on Django being present.  Hence, `test_settings.py` and the different envs.  I'm honestly not sure what's boilerplate, and what serves an actual purpose, given that I could find no `pii*` annotations, for instance.  Do you have any context, here?

**Comment by jmbowman** [comment]
The pii* annotations are for Django apps with models, to make sure that any personally identifiable information being stored in the database is documented accordingly.  This repo has no models, so that check shouldn't be needed here.

The Django setup in the doc build is usually needed if any of the code in this repo imports non-trivial Django code.  You could try removing it, but it may actually be needed to build the docs without errors.

And given the time constraints (we're trying to finish the edx-platform 2.2 release ASAP), I'd suggest deferring such additional cleanup work until after making a 2.2-compatible release.

**Comment by bradenmacdonald** [comment]
@arbrandes The docs are all empty, and we don't need the PII checker so you can rip those out. If that's going to take a while though, let's follow @jmbowman's advice and merge this now to remove the django requirement (or move it to `test` requirements, where the cookiecutter should have placed it in the first place!) and merge this, then do a follow-up PR to remove all that other unused boilerplate (django, docs, PII checker)

**Comment by arbrandes** [comment]
Alright, I'm taking a stab at the cleanup, and will report back promptly.

**Comment by bradenmacdonald** [comment]
Ah, I think the problem here is we used the django cookiecutter instead of the xblock cookiecutter. Hence all the unused stuff.

**Comment by arbrandes** [comment]
Now THAT makes a lot more sense, now. :)  I'll use that as a basis to rip stuff out.

**Comment by arbrandes** [comment]
Please don't merge yet: I want to test this both manually and via `make test` in the edx-platform virtualenv.

**Comment by bradenmacdonald** [comment]
> As a consequence, unit testing this repository must now be done in a Studio or LMS virtualenv, much like `lx-pathway-plugin`.

Honestly that makes more sense anyways - better to test in the environment you'll actually run in than a mock environment with a different runtime. The only reason we generally don't do that for XBlocks is that it makes it essentially impossible to run integration tests on CI. Hopefully one day edx-platform will be properly containerized and running tests of plugins like this on CI could be as simple as adding a couple of base containers (MySQL and LMS).

**Comment by arbrandes** [comment]
> better to test in the environment you'll actually run in than a mock environment with a different runtime

The pudding-proof was immediate: testing in the LMS venv exposed a Python3 test failure.  :)

I fixed this and a couple of other minor issues, and tested under Django 1.11 and Django 2.2, on latest master.  This is good to merge.

**Comment by bradenmacdonald** [comment]
:+1:

- [x] I tested this: did manual tests and ran unit tests under Django 1.11 (since this doesn't actually use Django, the version I tested with shouldn't matter.)
- [x] I read through the code: confirmed this removes Django. Still some minor ignored references in travis config file, pylintrc, and extract_translations make target, but that's OK as we aren't using those.
- [x] I checked for accessibility issues: N/A
- [x] Includes documentation: N/A

**Pull request merged**
