### PR TITLE
[FAL-2117]  Return Youtube video ID with Annotated video xblock data

### PR DESCRIPTION
**Pull request by toxinu**
This pull request is about returning the youtube video ID along with other view data so that the LX frontend can query the YouTube API to get extra details.

Note: This pull request should also increase the version number.

**Jira tickets**

- [FAL-2117](https://tasks.opencraft.com/browse/FAL-2117)

**Testing instructions**

Should be tested while reviewing internal PRs.

**Reviewers**

- [ ] @swalladge

### CODE REVIEW

**Comment by pomegranited** [comment]
@symbolist  Can you use your core committer powers to get this merged and deployed?

**Comment by toxinu** [comment]
@pomegranited This is still being reviewed by @swalladge as part of https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1455

**Review by symbolist — APPROVED** [review]
@toxinu Raul should be able to guide you on how to get this deployed on edx.org.

**Review by swalladge — APPROVED** [review]
@toxinu :+1:

- [x] I tested this: tested as part of https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1455
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation
- [x] I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository.

**Pull request merged**
